-- AlterTable: align KYC with schema (OCR fields)
ALTER TABLE "KYC" ADD COLUMN IF NOT EXISTS "dateOfBirth" TEXT;
ALTER TABLE "KYC" ADD COLUMN IF NOT EXISTS "docNumber" TEXT;
ALTER TABLE "KYC" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "KYC" ALTER COLUMN "docBackUrl" DROP NOT NULL;
